# Generated by Django 2.0.7 on 2019-10-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='media')),
                ('roll', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10)),
                ('registration', models.IntegerField()),
                ('phone', models.CharField(max_length=11, null=True)),
                ('session_start', models.DateField(verbose_name='Session start')),
                ('session_end', models.DateField(verbose_name='Session end')),
            ],
        ),
    ]
