# Generated by Django 2.0.7 on 2019-11-01 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearCompleted', models.DateField()),
                ('instituteName', models.CharField(max_length=100)),
                ('Field_of_expertise', models.CharField(default='C', max_length=100, verbose_name='Field of Interest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('gender', models.CharField(max_length=7)),
                ('qualification', models.CharField(max_length=350)),
                ('dateOfBirth', models.DateField()),
                ('shortBio', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('currentLocation', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=400)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ManyToManyField(to='students.EduLevel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
    ]
