# Generated by Django 2.0.7 on 2019-11-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_edulevel_studentinfo_studentqualification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='currentLocation',
            new_name='Address',
        ),
        migrations.RemoveField(
            model_name='edulevel',
            name='Field_of_expertise',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='shortBio',
        ),
        migrations.AddField(
            model_name='edulevel',
            name='Percentage',
            field=models.IntegerField(default=93),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edulevel',
            name='Qualification',
            field=models.CharField(default=10, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='courses',
            field=models.TextField(default='Python course', max_length=400),
            preserve_default=False,
        ),
    ]
