# Generated by Django 2.0.7 on 2019-11-01 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20191101_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentqualification',
            old_name='teacher',
            new_name='student',
        ),
    ]
