# Generated by Django 2.0.7 on 2019-11-01 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20191101_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='qualification',
        ),
    ]
