# Generated by Django 2.0.7 on 2019-11-01 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_studentinfo_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentqualification',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentInfo'),
        ),
    ]
