# Generated by Django 2.0.7 on 2019-11-01 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20191101_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentqualification',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
