# Generated by Django 2.0.7 on 2019-11-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20191101_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edulevel',
            old_name='student',
            new_name='student_id',
        ),
    ]
