# Generated by Django 2.0.7 on 2019-11-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20191101_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edulevel',
            old_name='student_id',
            new_name='student',
        ),
    ]
