# Generated by Django 2.0.7 on 2019-11-01 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_studentqualification_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentqualification',
            name='level',
        ),
        migrations.AddField(
            model_name='studentqualification',
            name='level',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.CASCADE, to='students.EduLevel'),
            preserve_default=False,
        ),
    ]
