# Generated by Django 2.0.7 on 2019-11-01 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20191101_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentqualification',
            name='level',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.EduLevel'),
        ),
    ]
