# Generated by Django 2.0.7 on 2019-11-01 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20191101_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentqualification',
            name='level',
        ),
        migrations.AlterField(
            model_name='studentqualification',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.EduLevel'),
        ),
    ]
