# Generated by Django 2.0.7 on 2019-11-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20191101_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
