# Generated by Django 2.0.7 on 2019-11-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_auto_20191101_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentqualification',
            name='level',
        ),
        migrations.AddField(
            model_name='studentqualification',
            name='level',
            field=models.ManyToManyField(to='students.EduLevel'),
        ),
    ]
