# Generated by Django 2.0.7 on 2019-11-01 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_auto_20191101_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentqualification',
            name='level',
        ),
        migrations.RemoveField(
            model_name='studentqualification',
            name='student',
        ),
        migrations.DeleteModel(
            name='StudentQualification',
        ),
    ]
