# Generated by Django 2.0.7 on 2019-11-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_auto_20191101_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edulevel',
            name='student',
        ),
        migrations.AddField(
            model_name='edulevel',
            name='student',
            field=models.ManyToManyField(to='students.Student'),
        ),
    ]
