# Generated by Django 2.0.7 on 2019-11-01 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_auto_20191101_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edulevel',
            name='student',
        ),
        migrations.AddField(
            model_name='edulevel',
            name='student',
            field=models.ForeignKey(default='Ravinder Kumar', on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
            preserve_default=False,
        ),
    ]
