# Generated by Django 2.0.7 on 2019-11-01 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_auto_20191101_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ManyToManyField(to='students.EduLevel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
    ]
