# Generated by Django 2.0.7 on 2019-11-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_studentqualification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentqualification',
            old_name='teacher',
            new_name='student',
        ),
    ]
