# Generated by Django 2.2.5 on 2019-09-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edulevel',
            old_name='grade',
            new_name='Marks',
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='shortBio',
            field=models.CharField(max_length=100),
        ),
    ]
