# Generated by Django 2.2.5 on 2019-09-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacherinfo_field_of_expertise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edulevel',
            old_name='Marks',
            new_name='grade',
        ),
    ]
