# Generated by Django 2.2.5 on 2019-09-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20190907_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinfo',
            name='Field_of_expertise',
        ),
        migrations.AddField(
            model_name='edulevel',
            name='Field_of_expertise',
            field=models.CharField(default='C', max_length=100, verbose_name='Field of Interest'),
        ),
    ]
