# Generated by Django 2.2.5 on 2019-10-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_auto_20190907_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edulevel',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='homeDistrict',
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='qualification',
            field=models.CharField(max_length=350),
        ),
    ]
