# Generated by Django 2.0.7 on 2019-11-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventgallery',
            old_name='city',
            new_name='place',
        ),
        migrations.RemoveField(
            model_name='eventgallery',
            name='country',
        ),
        migrations.AddField(
            model_name='meeting',
            name='name',
            field=models.CharField(default='college', max_length=100),
            preserve_default=False,
        ),
    ]
